### ISSUE TITLE
how to write in EDN string backslash and n

### ISSUE THREAD

**Issue by kraag22** [benmosher/edn-objc#26]
How can I write backslash and n characketr in edn string?

Something like 

    [@"\"\\\\n\"" ednObject]

this should return \ and "n" but returns newline...

**Comment by benmosher** [comment]
IIRC this is why the `\\\\` replace was at the end of the `markedString` replacements. 

What was the behavior you were seeing that you didn't expect, before your pull request?

**Comment by kraag22** [comment]
This behavior isn't something, that I have problem with. I just thought about it, when creating test for my pull request.

I created pull request because when you read file with EDN in clojure and there is "\\n" it is read as newline. That didn't worked in your library. It created \ and newline...

**Comment by benmosher** [comment]
I would think that "\\n" should be read into clojure as "\n", as it is an escaped slash followed by a letter 'n'.

I think your third test was not correct, per the edn-format spec. I have added a similar set of tests and will close this.

**Comment by benmosher** [comment]
Ahhh, okay, upon reflection, I see what you mean.

The actual backslash escapes need to be captured and not consumed by the \n, \t, etc.

I don't think your PR fully addresses this, but I'm pretty sure I broke your test with what I changed it to. Hadn't come into focus.

I'll try to fix it right now, thanks for bringing this up.
